# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]


  app.picture_uploader:
    class: AppBundle\Service\FileUploader
    arguments: ['pictures']

  app.makebig_filter:
    class: AppBundle\TwigFilter\MakeUpCase
    tags:
      - { name: twig.extension }
